### ISSUE TITLE
Chaning the value programmatically doesn't work

### ISSUE THREAD

**Issue by tzfrs** [andreruffert/rangeslider.js#181] opened 2015-10-21 17:18 UTC
In the onInit method I'm calling the following peace of code

    $slider.parent().find('input[type=range]').val($sliderVal['slider']).change();

However, the ranger is not chaning it's value.

    /// This returns 1, so it should work
    $slider.parent().find('input[type=range]').length 
    // This returns 20 (not "20", simply 20)
    console.log($sliderVal['slider']);

**Comment by andreruffert** [comment] 2015-10-21 18:54
Hi @tzfrs! First of all what are you trying to achieve? It's not clear to me so far...

**Comment by tzfrs** [comment] 2015-10-21 19:12
On your website you have this piece of code

![image](https://cloud.githubusercontent.com/assets/3509557/10647380/3db3eb36-7838-11e5-9030-d29cd55c69f2.png)

I guessed this would be the code snippet I have to use to achieve this

http://andreruffert.github.io/rangeslider.js/#js-example-change-value

As you can see, I'm selecting the input with the type range, setting a value, and calling the change method. Shouldn't it change now programmatically? Or is it the wrong method I'm using?

If it is the wrong one I have a suggestion for your website: Would be cool if you have the code next to the examples for easier copying and less confusion.

**Comment by andreruffert** [comment] 2015-10-21 21:24
K let's say you have a situation like this:

```js
var $myElement = $('#myElement');

// initialize a rangeslider.js instance
$myElement.rangeslider({...});
```

and now you want to change the value:

```js
$myElement.val(10).change();

// => should be `10` now
console.log($myElement[0].value);
```

I guess the problem is this:

> In the onInit method I'm calling the following peace of code
`$slider.parent().find('input[type=range]').val($sliderVal['slider']).change();`

If you change the value of an element which gets initialized at the moment there could be some race conditions...

Why are you changing the value on initialization? I would set the value right before!
Directly in the markup or with JS unless it's not possible otherwise.

**Comment by andreruffert** [comment] 2015-10-29 11:23
Closing because of no feedback...

**Closed by andreruffert** 2015-10-29 11:23 UTC
Labels: support

**Comment by tzfrs** [comment] 2015-10-30 10:48
Sorry for the late answer! 

The reason I want to change the value at initialization is the following: A user uses the slider and submits a form, then he comes back to the site. His choice however is saved in the session. Currently I'm reading this session and setting the value of the slider to the value he selected, however I thought there would be a way to do that with the rangeslider directly

**Comment by andreruffert** [comment] 2015-11-02 10:46
> The reason I want to change the value at initialization is the following: A user uses the slider and submits a form, then he comes back to the site. His choice however is saved in the session. Currently I'm reading this session and setting the value of the slider to the value he selected, however I thought there would be a way to do that with the rangeslider directly

There is a way of doing it directly with rangeslider.js but I would recommend to set the value from the session directly to the input e.g.
```html
<input type="range" value="{{sessionValue}}">
```

**Comment by tzfrs** [comment] 2015-11-02 10:47
Yep, that's what I'm currently doing. Was just wondering how it would work in a JS way. But I'm using the PHP solution now. Thanks anyway

**Comment by andreruffert** [comment] 2015-11-02 10:50
Ok kewl you're welcome! :v:
