### ISSUE TITLE
Fails to init if polyfill: false is not specified

### ISSUE THREAD

**Issue by aiaf** [andreruffert/rangeslider.js#177] opened 2015-09-28 12:45 UTC
Must be initialized with at least

`{ polyfill: false }`

for this to work (Chrome 45, Firefox 40). If you supply no arguments to .rangeslider() it fails silently. This should be documented somewhere.

**Comment by Chrisriis** [comment] 2015-10-01 17:34
I can confirm this issue. Used some time to debug it because there's no error returned as mentioned.

**Comment by brianO3world** [comment] 2015-10-02 19:49
Confirmed this is an issue as well

**Comment by andreruffert** [comment] 2015-10-04 17:18
Hey guys :) 

rangeslider.js is developed to be a [polyfill](https://remysharp.com/2010/10/08/what-is-a-polyfill) for the `<input type="range>"` element. Which means if the browser has no [support](http://caniuse.com/#feat=input-range) for the element rangeslider.js provides the functionality you expect.
But of course you could also use it in browsers which support the  `<input type="range>"` element by setting `{ polyfill: false }`.

I hope this makes it a bit more clear for you. If you think it's confusing to understand and have a suggestion to make it better to understand in the [docs](https://github.com/andreruffert/rangeslider.js/tree/gh-pages) feel free to make a pr for that or just comment right here.

:v:

**Comment by andreruffert** [comment] 2015-10-29 11:24
Closing because of no feedback...

**Closed by andreruffert** 2015-10-29 11:24 UTC
Labels: needs: feedback, type: docs

**Comment by brianO3world** [comment] 2015-10-29 13:19
Apologies, I just saw this again. The clarification you provided above was perfect. For me, I think the issue is more making that clear in the usage notes. I specifically needed a custom styled rangeslider, but since I was using a browser that supported it, nothing was rendering.

More a point of documentation than it being incorrect. Sorry for the confusion. And thanks for taking the time to review this!
